production:
  adapter: postgresql
  database: {{ redmine_database_name }}
  host: {{ redmine_database_host }}
  username: {{ redmine_database_user }}
  password: {{ redmine_database_password }}
  encoding: utf8
